title:   Isilay Guzel
logo: "/images/Profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br><br>
  "Welcome to my portfolio! Here you will find examples of my work, skills, and experiences. I hope you enjoy exploring and getting to know me better."
  <br><br><br>
  <a href="https://www.linkedin.com/isilayguzel/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https:https://public.tableau.com/app/profile/isilay7617">View My Tableau Work Samples</a>
  <br><br>
  <a href="https://www.notion.so/Portfolio-Your-Name-d2586380c5cc4dde97ad067342e1b169">View My Notion Portfolios</a>
  
theme: jekyll-theme-minimal   
 
